# Generated by Django 5.1.6 on 2025-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
