# Generated by Django 5.1.6 on 2025-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
